/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seng.monsters;

import java.awt.EventQueue;

import seng.monsters.ui.gui.GUI;

public class App {
    public static void main(String[] args) {
        EventQueue.invokeLater(() -> {
        		final var gui = new GUI();
        	});
    }
}
